name: fre-python-tools-dev
channels:
  - conda-forge
dependencies:
  - python>=3.6 # oldest python officially supported security-wise
  - cdo
  - python-cdo
  - cmor
  - xarray
  - metomi-isodatetime
  - pytest
  - pip
