name: fre-python-tools-dev2
channels:
  - conda-forge
dependencies:
  - python=3.10 # oldest python officially supported security-wise
  - cdo
  - python-cdo
  - cmor
  - xarray
  - metomi-isodatetime
  - pytest
  - pip
