package:
  name: fre-python-tools
  version: 0.0.1

source:
  path: .

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - metomi-isodatetime
    - cmor
    - generate_time_averages

test:
  imports:
    - fre_python_tools
    - metomi.isodatetime
    - cmor
    - generate_time_averages

about:
  home: https://github.com/NOAA-GFDL/fre-python-tools
  license: LGPL-3.0
  license_file: LICENSE.md
  summary: Python-based tools and interfaces to be used by FRE workflows
