name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: pylint generate_time_averages
      continue-on-error: true
      run: |
          pylint --disable too-few-public-methods --disable too-many-arguments --module-naming-style camelCase --clear-cache-post-run y $(git ls-files 'fre_python_tools/generate_time_averages/*.py')
    - name: pylint cmor_mixer
      continue-on-error: true
      run: |
          pylint $(git ls-files 'fre_python_tools/cmor_mixer/*.py')
